version: '3.8'

services:
  backend:
    env_file:
    - ./.env
    build: ./
    command: ./backend
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
      - SALT=uh3yf8r7g17312341234d
      - SMTP_PASSWORD=drYk8ykHR399
      - JwT_SINGING_KEY=ak*sdhf$187y@foiu1e
      - FIREBASE_AUTH_KEY=AAAA8QK0YKY:APA91bE30uRqIgS1OzNsz6wEEcJRaPl6yw7hfhFWsOhFFe-vb8q3_deqokyXi7Zx0p1y5Ijc2dVNUb1XpM94P5a42ndCwr9kZYfEvCSmsZkrkGks3mlsFmUA6z7h2M-W-Y3Rtj2-N2aZ

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432