https:
    port: "8080"
    cert: ".certificate//cert.pem"
    key: ".certificate//key.pem"

db:
    username: "postgres"
    host: "localhost"
    port: "5432"
    dbname: "postgres"
    sslmode: "require"


template:
    EmailConfirmation: "htmlTemplate//template.html"


