https:
    host: "51.250.24.31"
    port: "65000"
    cert: ".certificate//cert.pem"
    key: ".certificate//key.pem"

db:
    username: "postgres"
    host: "localhost"
    port: "5436"
    dbname: "postgres"
    sslmode: "disable"

smtp:
    from: "bip.project@rambler.ru"
    smtpHost: "smtp.rambler.ru"
    smtpPort: 587

template:
    EmailConfirmation: "htmlTemplate//template.html"


