https:
    host: "158.160.27.251"
    port: "443"
    cert: ".certificate//cert.pem"
    key: ".certificate//key.pem"

db:
    username: "postgres"
    host: "localhost"
    port: "5432"
    dbname: "postgres"
    sslmode: "disable"

smtp:
    from: "bip.project@rambler.ru"
    smtpHost: "smtp.rambler.ru"
    smtpPort: 587

template:
    EmailConfirmation: "htmlTemplate//template.html"


